### ISSUE TITLE
BAC-117 ⁃ Add dependency management

### ISSUE THREAD

**Issue by alika** [samsung-cnct/container-technical-on-boarding#12]
Add [dep][1] to manage vendored dependencies.

[1]: https://github.com/golang/dep

**Comment by cwazy1** [comment]
➤ Alika Larsen commented:

Work for this was completed (pr-submitted, pr-approved, merge to master) on [PR#14](https://github.com/samsung-cnct/container-technical-on-boarding/pull/14).
